title = "Relatório Semanal de Performance de Caixas"

[segunda]
horas = [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
horas_totais = ["00:00", "00:00", "01:03", "01:01", "01:40", "01:52", "01:25", "01:22", "01:14", "01:24", "02:13", "01:50", "02:25", "01:39", "00:41", "00:01", "00:00", "00:00"]
vendas_euros = [0, 0, 1081, 966, 1767, 3889, 1360, 1365, 1195, 1178, 2309, 1869, 2534, 1707, 739, 5, 0, 0]
num_caixas = [0, 0, 0, 2, 2, 3, 2, 2, 2, 2, 3, 4, 3, 3, 1, 1, 0, 0]
performance = [0, 0, 1038, 958, 1067, 2036, 916, 906, 957, 870, 992, 945, 961, 955, 1196, 195, 0, 0]

[terca]
# Valores estimados (Média entre Segunda e Quarta)
horas = [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
horas_totais = ["00:00", "00:00", "00:52", "01:17", "01:51", "02:02", "01:53", "01:43", "01:18", "01:31", "02:29", "02:11", "02:19", "01:38", "00:45", "00:05", "00:00", "00:00"]
vendas_euros = [0, 0, 829, 1255, 1934, 3045, 1856, 1692, 1366, 1379, 2545, 2262, 2454, 1716, 769, 14, 0, 0]
num_caixas = [0, 0, 1, 2, 3, 3, 3, 2, 2, 2, 4, 3, 3, 3, 1, 1, 0, 0]
performance = [0, 0, 915, 980, 1027, 1536, 957, 960, 1034, 870, 1014, 970, 974, 967, 1014, 294, 0, 0]

[quarta]
horas = [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
horas_totais = ["00:00", "00:01", "00:42", "01:33", "02:02", "02:13", "02:22", "02:05", "01:22", "01:39", "02:45", "02:33", "02:13", "01:37", "00:50", "00:08", "00:00", "00:00"]
vendas_euros = [0, 0, 577, 1544, 2101, 2202, 2353, 2020, 1537, 1581, 2781, 2655, 2375, 1725, 799, 23, 0, 0]
num_caixas = [0, 0, 1, 2, 4, 3, 3, 3, 3, 3, 4, 3, 3, 3, 2, 1, 0, 0]
performance = [0, 0, 792, 1001, 987, 1037, 999, 1015, 1111, 870, 1037, 995, 988, 980, 833, 394, 0, 0]

[quinta]
horas = [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
horas_totais = ["00:00", "00:00", "00:00", "00:58", "01:19", "01:46", "02:19", "01:59", "01:53", "01:19", "01:28", "02:21", "01:51", "02:10", "01:33", "00:46", "00:04", "00:00", "00:00"]
vendas_euros = [0, 0, 0, 494, 1166, 1557, 2132, 1896, 2146, 1156, 1907, 2358, 1810, 2894, 1761, 774, 4, 0, 0]
num_caixas = [0, 0, 0, 0, 2, 3, 3, 4, 3, 2, 2, 4, 3, 3, 3, 1, 1, 0, 0]
performance = [0, 0, 0, 581, 922, 859, 981, 1025, 1143, 956, 1038, 984, 866, 1123, 981, 924, 173, 0, 0]

[sexta]
horas = [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
horas_totais = ["00:00", "00:00", "00:00", "01:13", "01:46", "02:16", "02:28", "02:23", "01:47", "01:46", "02:24", "02:12", "02:48", "02:42", "02:09", "01:07", "00:18", "00:00", "00:00"]
vendas_euros = [0, 0, 0, 1303, 2083, 2261, 2621, 2447, 1728, 2146, 2740, 2357, 3056, 2998, 2173, 1329, 215, 0, 0]
num_caixas = [0, 0, 0, 1, 2, 3, 4, 3, 2, 3, 4, 3, 4, 3, 3, 2, 1, 0, 0]
performance = [0, 0, 0, 1015, 1136, 1051, 960, 1053, 871, 1193, 1120, 982, 1057, 1005, 1013, 1021, 1233, 0, 0]

[sabado]
horas = [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
horas_totais = ["00:00", "00:01", "00:40", "01:20", "02:40", "03:01", "02:40", "01:39", "01:52", "02:28", "02:02", "02:28", "02:01", "01:20", "00:46", "00:07", "00:00", "00:00"]
vendas_euros = [0, 0, 495, 1547, 3127, 3640, 3543, 1832, 2010, 3006, 2154, 2616, 2351, 1572, 947, 45, 0, 0]
num_caixas = [0, 0, 1, 3, 4, 4, 3, 2, 2, 3, 3, 4, 3, 2, 2, 1, 0, 0]
performance = [0, 0, 867, 1041, 1174, 1136, 1244, 1055, 1032, 1203, 1025, 996, 1088, 1061, 1059, 969, 0, 0]

[domingo]
horas = [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
horas_totais = ["00:35", "01:03", "02:02", "02:52", "02:22", "01:35", "01:34", "02:02", "02:40", "02:38", "01:55", "01:13", "00:42", "00:12", "00:00", "00:00"]
vendas_euros = [584, 1175, 2453, 3020, 2310, 1379, 1852, 2711, 3121, 2912, 2240, 1224, 693, 109, 0, 0]
num_caixas = [0, 2, 4, 4, 3, 3, 2, 4, 4, 3, 3, 2, 1, 1, 0, 0]
performance = [875, 1115, 1163, 1007, 1065, 903, 1113, 1221, 1101, 1042, 1080, 999, 1131, 1126, 0, 0]
